name: Auto Deploy Angular Templates to GitHub Pages

on:
  push:
    branches-ignore:
      - gh-pages
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app for this branch
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          echo "🚧 Building template for branch: $BRANCH_NAME"
          npm run build-template -- $BRANCH_NAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
